binary: true
blocksize: 10
build_blocks:
  binary: true
  csv: true
data_version: develop
indexes:
  athletes:
  - Athlete_ID
  athletic_events:
  - Athlete_ID
key: Athlete ID
rootdir: C:\Users\Hrishi\PycharmProjects\relational_db
