binary: false
blocksize: 10
build_blocks:
  binary: true
  csv: true
data_version: develop
experiment_mode: true
indexes:
  athletes:
  - Athlete_ID
  - NOC
  athletic_events:
  - Athlete_ID
key: Athlete ID
rootdir: /Users/wesrobbins/Desktop/fall2021/540/hw1-repo
