binary: false
blocksize: 10
build_blocks:
  binary: true
  csv: true
data_version: develop
indexes:
  athletes:
  - Athlete_ID
  athletic_events:
  - Athlete_ID
rootdir: /Users/wesrobbins/Desktop/fall2021/540/hw1-repo
